.\" $Id$
.TH barch 1
.SH NAME
barch \- backup archive utility
.SH SYNOPSIS
.B barch
.I <operation>
.I [options]
.SH DESCRIPTION
barch is an archive utility specifically designed with the needs of the
backup and restore process in mind.
.SH OPTIONS
Most of the following options were adopted from
.B tar
in order to ease migration from one tool to the other.
.SS Operation Modes
.TP
.B -c, --create
Create a new archive.
.TP
.B -t, --list
List the contents of an archive.
.TP
.B -x, --extract
Extract files from an archive.
.SS Operation Modifiers
.TP
.B -G, --incremental
When creating an archive, record all of the files encountered in each
matching directory in the archive file, for use when extracting the
archive.  When extracting files from an archive, the list of files in
each matching directory is compared against the files in the
corresponding destination directory.  All files present in the
destination that are not listed in the archive are removed.
.TP
.B -g FILE, --listed-incremental=FILE
Enables incremental mode as described above, but also records a snapshot
of the time when the archive was started and all directories traversed
into the named file.  If the snapshot file previously existed, the
contents of the output archive are limited to files that have been
modified in any way (including being renamed) more recently than the
timestamp in the file and the entire contents of directories that have
been renamed or replaced.
.TP
.B --differential=FILE
Similar to the listed-incremental mode above, this mode uses the
snapshot file to determine what files to archive, but does not update
the file when the backup process is complete.
.TP
.B --overwrite-files
When extracting an archive, overwrite files directly instead of using
temporary files.
.TP
.B -j, --bzip2
Filter (compress or uncompress) the archive using
.BR bzip2 .
.TP
.B -z, --gzip
Filter (compress or uncompress) the archive using
.BR gzip .
.TP
.B -Z, --compress
Filter (compress or uncompress) the archive using
.BR compress .
.SS Archive I/O Options
.TP
.B -f FILE, --file=FILE
Archive filename (defaults to standard input when reading archives, or
standard output when writing archives).
.SS Local File Selection
.TP
.B -C PATH, --directory=PATH
Change to named directory after opening archive and before reading or
writing files.
.TP
.B --exclude=PATTERN
File names to exclude files, given as a glob pattern.
.TP
.B -X FILE, --exclude-from=FILE
Exclude patterns listed in the named file.
.TP
.B --include=PATTERN
Include files, given as a glob pattern
.TP
.B -I FILE, --include-from=FILE
Include patterns listed in the named file
.TP
.B --patterns-from=FILE
Ex/include patterns listed in the named file.  Each line in the file
contains one pattern, prefixed by either
.B +
for files to include, or
.B -
for files to exclude.  Lines starting with
.B #
are ignored.  The patterns are applied in order, and the first matching
pattern determines the outcome.
.TP
.B -P, --absolute-names
Don't strip leading '/'s from file names
.TP
.B -h, --dereference
Dump instead the files symlinks point to
.TP
.B -N FILE, --newer=FILE, --after-date=FILE
Only store files newer than the given file
.TP
.B --one-file-system
When creating an archive, do not recurse into directories that are
located on different filesystems from their parents.  The directory
itself is still recorded in the archive, for compatibility with
.BR tar .
Note that directories specifically listed on the command line are always
archived.
.SS Informative Output
.TP
.B -v, --verbose
Show more information about progress.  This option may be used multiple
times.
.TP
.B --checkpoint
Print directory names as they are processed.
.TP
.B --totals
Output the total number of bytes written after the archive is created.
.SH WARNINGS
The default behavior of
.B barch
is to create temporary files and then rename them on top of the
destination file.  This default behavior is required to overwrite files
that are in use (ie mmaped), but it destroys any hard links to files
being written.  Use
.B --overwrite-files
if this is a problem.
